apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tech-challenge-app.fullname" . }}
  labels:
    app.kubernetes.io/name: tech-challenge-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tech-challenge-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tech-challenge-app
    spec:
      containers:
        - name: tech-challenge-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}