apiVersion: v1
kind: Service
metadata:
  name: {{ include "tech-challenge-app.fullname" . }}
  labels:
    app.kubernetes.io/name: tech-challenge-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: tech-challenge-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}